README.md
Using Lanyard to fetch my Discord avatar and display a listening status (right after my name) once I'm active on Spotify.
=> Add eri.gg to README

README.md
Added [kevinthomas.codes](https://kevinthomas.codes) to Lanyard's community projects.
Note: Lanyard status only shows up when I'm listening to music, it isn't visible when I'm not. Example here - https://twitter.com/trustedmercury/status/1402068764707983360/
=> Added my portfolio to community projects

README.md
Hawser is Lanyard API wrapper for Python. Supports both REST and WebSocket Methods. 
Links: [PyPi](https://pypi.org/project/hawser/) | [GitHub](https://github.com/5elenay/hawser)
Edit: Typo
=> Added Hawser

README.md
Added [anaxes.xyz](https://anaxes.xyz) to the websites using lanyard list.
Proof: 
Please note: The "listening to" section only appears when I am listening to Spotify. The "status" icon located next to the header title, appears all the time and updates accordingly.
=> Added anaxes.xyz to lanyard use list.

README.md
This PR adds the website maisakurajima.netlify.app to the Readme File.
It uses Lanyard to pull the data on the [`/team`](https://maisakurajima.netlify.app/team) page.
=> Added maisakurajima.netlify.app to Readme

README.md
added use-listen-along to the community projects list :)
also, is it possible for lanyard to return the progress of a song? e.g. `{ "progress_ms": 193200 }`
=> feat(readme): add use-listen-along to community projects

README.md
Adding back my website as I am unsure as to why it was removed. 
Proof of Lanyard's REST API being used within my website:
<details>
<summary>🚀 Activity Card towards the bottom of my website</summary> 
</details>
<details>
<summary>🌏 Small status' at top of the page.</summary> 
</details>
=> Added "Anaxes.xyz" to 'used by' list.

.dockerignore, Dockerfile, README.md, config/prod.exs, config/runtime.exs
I added Docker support! I've written some instructions in the readme. I'm not very familiar with elixir but I figured I had to create a `runtime.exs` so it would load `BOT_TOKEN` on runtime. I found more about that here: https://fly.io/docs/getting-started/elixir/#runtime-config
The final image is about 92 MB which is great for a Docker image. I'm not sure if you're familiar with publishing to Docker hub, but I'm happy to help. I use Docker daily and I'll gladly make a github actions pipeline if you'd like.
Finally, thank you for making this! I really love Lanyard.
I have it self hosted here: https://lanyard.cutelab.space
Which my site is using, reducing some load: https://maki.cafe
=> Add Docker support for self hosting

README.md
Changed the main domain of my site to dstn.to so I figured I'd change here to so it's not just a redirect.
=> Changing dustin.sh to dstn.to

README.md
This PR fixes the line wrapping on the Community Projects section while maintaining how it looks, as well as adds the [svelte-lanyard](https://github.com/iGalaxyYT/svelte-lanyard) project.
This will break any existing open PRs that modify the Community Projects section.
There is an existing PR open that you might prefer, although it changes the section to a list instead of maintaining how it currently looks: https://github.com/Phineas/lanyard/pull/89
Let me know if I should separate this PR. I just didn't want to leave the section in its current state with broken line wrapping when I added my own project, haha.
=> Fix Community Projects & add svelte-lanyard

lib/api/routes/v1/users.ex
This fixes the 500 HTTP error when calling the PUT and DELETE endpoints.
Was caused by the user id being stringed, but the functions on the kv interface take an integer.
=> Converting user_id to integer before passing to kv set and del

.github/workflows/docker-image.yml, README.md
Meant to get this in the last PR, but was merged right before I pushed it.
It's obviously not required to build the docker image if you want to run the same version as production, so adding a hint to make that clear.
Also changes workflow to only run on main branch push
=> Adding hint that you can skip the build step

README.md
I added `restart: always` and `depends_on: redis`. I also moved redis up since its a dependency on lanyard. Thank you so much for updating the read me. My instance broke on my server and was able to immediately fix it.
=> Updated Docker on README.md

README.md
Old site: https://nickdev.org
New site: https://notnick.io
=> Change website

README.md
`application_id` is a `string`, not a `number`
=> fix example api response in README

README.md
adds [sk-lanyard](https://github.com/nebulatgs/sk-lanyard), a SvelteKit Lanyard library, to Community Projects
=> add sk-lanyard to community projects

.github/workflows/docker-image.yml
Passing DOCKER_PASSWORD via stdin is more secure, since arguments are visible in the process tree.
It might not make a difference, but passing data through stdin involves passing it through a file descriptor which can be read by using standard io calls. Command line arguments are kept in a processes `argv` in memory, any unprivileged can access that address of memory to view the arguments.
=> Pipe docker password instead of using it as an argument

lib/presence/spotify.ex
`spotify_activity` has no `state` if the user is listening to a local file, resulting in a crash.  
This PR changes build_pretty_spotify to ensure the spotify activity has `state`, even if there's no data  
This will prevent lanyard from freezing for a while whenever you play a local file.  
Here's an example of the error that was occuring:
```
21:23:08.744 [error] GenServer :"presence:303267459824353280" terminating
** (KeyError) key :state not found in: %{id: "spotify:1", name: "Spotify", type: 2, details: "EMPTY DIARY (instrumental)", timestamps: %{start: 1715635386950, end: 1715635586950}, assets: %{large_text: "UNBEATABLE: DEMO TAPES"}, created_at: 1715635388913, party: %{id: "spotify:303267459824353280"}}
(lanyard 0.1.0) lib/presence/spotify.ex:5: …
```
=> Prevent crash with Spotify local files

lib/api/routes/quicklinks/discord_cdn.ex
If the avatar doesn't begin with a_ it's not animated so when .gif is requested it will fail, this PR defaults the request to use .jpg in that case so that it doesn't fail.
=> Default to jpg over gif on quicklinks when not animated

README.md
I updated the Table of Contents to correct the "Used by" shortcut to direct to showcase as well as changing the the name to "Showcase" as intended. I also updated my old domain venqoi.lol to my new domain loefey.world
=> Updated table of contents and showcase

README.md
causes the [documentation site](https://lanyard.eggsy.xyz) to display the site incorrectly and lead to a dead address
=> (fix): change littleprinceonu to littlepriceonu
