Phineas/lanyard

- README.md
Added my personal site to the README.
> add lafond.dev

- README.md
> chore(readme): add eggsy.xyz

- README.md
Added my new personal website to the Readme, in which I also implemented Online/Offline Status using Lanyard. In addition to that, it shows if I'm browsing StackOverflow or what I'm listening to on YouTube Music using Lanyard (and PreMiD to show it in my Presence)
> Added crugg.de to Readme

- README.md
My implementation supports Spotify & normal statuses as well as shows when I'm online without a status, online mobile, in Do Not Disturb mode, etc.
> Add igalaxy.dev to README

- README.md
has a box containing lanyard information
> add itspolar.dev

- README.md
> add v30xy.github.io

- README.md
The activity is displayed in the bottom left corner. It supports Spotify and games. It doesn't show anything, when I am doing nothing or when I am offline.
> Add vasc.dev

- README.md
Using Lanyard to show what I'm listening on Spotify. Here's a screenshot shows that it works perfectly :100:
> Add arda.codes to README

- lib/api/router.ex
- lib/api/routes/discord.ex
- lib/api/routes/users.ex
- lib/api/util.ex
- lib/bot/discord_bot.ex
- lib/gateway/client.ex
- lib/gateway/heartbeat.ex
- lib/gateway/utility.ex
- lib/lanyard.ex
- lib/presence/presence.ex
- lib/socket/socket_handler.ex
Hey! it took me a while to find a way to redirect requests in Elixir, but here it is. I hope it's okay by your standards. There was a conflict but I managed to fix it. I ran `mix format`, I can't revert that commit unless you don't want the changes. 🙏
> feat: add /discord route to redirect to the discord server

- .gitignore
- lib/api/router.ex
- lib/api/routes/users.ex
- lib/api/routes/v1/router.ex
- lib/api/routes/v1/users.ex
- lib/api/util.ex
- lib/gateway/client.ex
- lib/presence/presence.ex
- [Fixed match bug & Folder structure has been improved for router](https://github.com/5elenay/lanyard/commit/baa2953f35d17810f16f81e8b066883942675a77)
- [Upgraded gateway version to latest (v9)](https://github.com/5elenay/lanyard/commit/812d5dd66ddd3c4255c74a411f53f3b6060f95f4)
Tested both WebSocket and REST API, Works perfect without any bugs.
> Fixed Router Bugs, Upgraded Gateway to v9

- README.md
Is a bit of a mess but will clean up when I have the time. But proof below with a request to lanyard API
https://i.imgur.com/DZwpzmq.png
> proof in images

- README.md
> Add "JS-Lanyard" to community projects.

- README.md
> 📝 Add "go-lanyard" to "Community Projects" section

- README.md
the usage of lanyard is contained within one of the api routes here: https://github.com/punctuations/presence/blob/9183e6cec55942fef3786fe804b424c9c60524cf/pages/api/discord/user/%5Bid%5D.ts#L33
used to generate images with rich presence.
> feat(readme): add presence to 'used by' list

- README.md
<h3 align="center">added my website [d3r1n.com](https://d3r1n.com)</h3>
> Add new website [d3r1n.com]

- README.md
> Add cnrad.dev to site list

- README.md
Thank you so much for this awesome program. It's a main piece to my website.
I'm probably going to look into self-hosting so that I'd save up a little bit of bandwidth!
> Add maki.cafe

- README.md
- Added command to run redis
- Added redis service to docker compose example
> Updating docker instructions to include redis

- README.md
> chore(readme): fix docs

- lib/bot/command_handler.ex
since it's easier to get it to help ya
> feat: alias kv as help

- README.md
I switched to the new domain. Because my old domain is useless now.
> chore: update my old domain

- README.md
Hi,
I added Lanyard to my website for showing my data.
(https://github.com/ReXulEc/v1/blob/main/src/components/Widget/Discord.vue)
Best regards,
Mert Doğu.
> add: rexulec.com to 'README'

- README.md
i did a lanyard
picture of when it's actually working is below
> add zeromomentum.me

- README.md
Would like to request my website to be added to the README.md list
Status indicator uses the lanyard API to display if currently online, idle, dnd and offline.
Website source: https://gitlab.com/voltages/voltages.me
Component using lanyard: https://gitlab.com/voltages/voltages.me/-/blob/main/src/components/Status.tsx
> docs: add https://voltages.me to README.md list

- README.md
Updated my domain as the old one is no longer used.
> fix(readme): fixed my domain

- README.md
added tysm.dev to website list 
used for pfp, status color, status text, currently playing
> Add website tysm.dev 

- README.md
Denyard is API wrapper for Lanyard.
Supports REST & WebSocket
> add denyard

- README.md
https://github.com/pxseu/lanyard-ui
> feat: add lanyard-ui project

- README.md
> Revert "Added itsdestiny.me"

- README.md
Hello. I am sorry about that. I have not updated the site in a while and I did not realised that what I used to obfuscate my code was causing browser issues. I have deobfuscated the code and my site will keep it like that. Sorry Again.
> Added itsdestiny.me (Fixed)

- README.md
> Added My Website

- README.md
I added mine and the lanyard part of my website is here: https://github.com/Noirscode/webpage/blob/main/components/About/index.tsx#L12
note: i use lanyard with [react-use-lanyard](https://www.npmjs.com/package/react-use-lanyard) module made by @barbarbar338
> added: my website

- README.md
You can see how I use Lanyard [here](https://github.com/2m4u/my-portfolio)
> Added my website - please merge :)

- README.md
Just adding my community repo to the readme (:
> Include discord-status-action

- README.md
Update README.md
Added My Portfolio at [itsmebravo.dev](itsmebravo.dev) as Used By
> Added My Portfolio as Used By

- README.md
> added my personal website to the Used By on README

- README.md
added my website (https://rovi.me) to the readme
> Added my website to the readme

- README.md
[![](https://get.snaz.in/2odXEkW.png)](https://snazzah.com)
> Add snazzah.com to Used By list

- README.md
> Add aidak.tk to "Used By"

- README.md
> Adds itsnp.cf to the showcase

- README.md
> Add sayanzyx.netlify.app to the "used by" list

- README.md
Add [lanyard card example](https://lanyard-card-example.netlify.app) to the used by list. 
This is a basic example of a profile card using the Lanyard API
> Add card example to used by list

- README.md
well, seems like we are not adding website url to main repo so here's what i did instead
> chore: add lanyard-web to readme

- README.md
Currently, it syncs my platform info, Spotify info, name, tag, avatar, and status with emoji to my webpage using Lanyard
> Added My Webpage on the "Used By"

- README.md
> add brandons.place

- README.md
uses lanyard to scrape osu! song information from discord.
> Added osu!nowplaying

- README.md
> add plskz.me

- README.md
I'm using Lanyard to fetch my discord pfp and display listening status & game status
> Add erdem.js.org to README

- README.md
> add ushie.dev

- README.md
> Add lonelil.dev

- README.md
Added [landart](https://pub.dev/packages/landart) to the list of community projects!
> feat(readme): add `landart` to community projects
